In [3]:
import tensorflow as tf
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model

In [7]:
## load the trained model, scaler pickle and onehot
model=load_model('model.h5')

##load the encoder and scaler pickle files
with open('one_hot_encoder_geo.pkl','rb') as file:
    one_hot_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [9]:
## example input data for prediction
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 2,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [10]:
## one hot encode the 'Geography' column
geo_encoded=one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\kavya gupta\OneDrive\Desktop\DL Projects\Churn Modelling\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [12]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,2,60000,2,1,1,50000

In [24]:
print(type(label_encoder_gender))
print(label_encoder_gender.classes_)
print(input_df['Gender'])

<class 'sklearn.preprocessing._label.LabelEncoder'>
['Female' 'Male']
0    1
Name: Gender, dtype: int64

In [25]:
##encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

ValueError: y contains previously unseen labels: 1

In [19]:
## contatination one hot encoded
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,2,60000,2,1,1,50000,1.0,0.0,0.0

In [20]:
## scaling the input data
scaled_input=scaler.transform(input_df)
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -1.04241787, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [21]:
## prediction
prediction=model.predict(scaled_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

array([[0.03312001]], dtype=float32)

In [22]:
prediction_prob=prediction[0][0]

In [23]:
prediction_prob

np.float32(0.03312001)

In [24]:
if prediction_prob > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.

In [1]:
print(label_encoder_gender.classes_)

NameError: name 'label_encoder_gender' is not defined